GET https://bonsai-health.shuttleapp.rs/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidGVzdCIsImV4cCI6MTY2NzY1MTExMH0.hMujQt5l_eoKOOi07ZlyBYe1mTQsmrCUbP2USBB3xds
// NOTE: Token is here for testing purposes