GET http://127.0.0.1:8000/user HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidGVzdCIsImV4cCI6MTY2NzY1MzIxNn0.RCpslqn2QdsuXwgBK7XAhmsHjwv32FIh-Sfn-YuAeiU
// NOTE: Token is here for testing purposes