POST http://127.0.0.1:8000/user/edit_tree HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoidGVzdCIsImV4cCI6MTY2NzY1MzIxNn0.RCpslqn2QdsuXwgBK7XAhmsHjwv32FIh-Sfn-YuAeiU
Content-Type: application/json

// NOTE: Token is here for testing purposes
[
  {
      "type": "extension",
      "length": 20,
      "angle": 5,
      "children": [
          {
              "type": "extension",
              "length": 50,
              "angle": 0,
              "children": [
                  {
                      "type": "leaf",
                      "children": [],
                      "taskId": "123981628362",
                      "time": 1667646852281
                  },
                  {
                      "type": "extension",
                      "length": 50,
                      "angle": 0,
                      "children": [
                          {
                              "type": "extension",
                              "length": 50,
                              "angle": -38,
                              "children": [
                                  {
                                      "type": "extension",
                                      "length": 20,
                                      "angle": 22,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667646894906
                                          },
                                          {
                                              "type": "extension",
                                              "length": 20,
                                              "angle": 22,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667646896183
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 25,
                                                      "angle": 31,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646949216
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646948035
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 25,
                                                      "angle": -29,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646957463
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 25,
                                                              "angle": -29,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667646961622
                                                                  },
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 25,
                                                                      "angle": 10,
                                                                      "children": [
                                                                          {
                                                                              "type": "leaf",
                                                                              "children": [],
                                                                              "taskId": "123981628362",
                                                                              "time": 1667647916030
                                                                          }
                                                                      ],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667646962130
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667646957931
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646955896
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667646895723
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667646894378
                                  },
                                  {
                                      "type": "extension",
                                      "length": 20,
                                      "angle": -41,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667646900956
                                          },
                                          {
                                              "type": "extension",
                                              "length": 20,
                                              "angle": -22,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667646904633
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 20,
                                                      "angle": -22,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646906634
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646906180
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 20,
                                                      "angle": 16,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646910839
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646910317
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 25,
                                                      "angle": 45,
                                                      "children": [
                                                          {
                                                              "type": "extension",
                                                              "length": 25,
                                                              "angle": 45,
                                                              "children": [
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 25,
                                                                      "angle": -33,
                                                                      "children": [
                                                                          {
                                                                              "type": "leaf",
                                                                              "children": [],
                                                                              "taskId": "123981628362",
                                                                              "time": 1667647918421
                                                                          }
                                                                      ],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667646970231
                                                                  },
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667646977749
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667646967679
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 25,
                                                              "angle": -8,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667646982054
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667646973938
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646966791
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667646904227
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667646900432
                                  },
                                  {
                                      "type": "extension",
                                      "length": 20,
                                      "angle": -2,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667648011376
                                          },
                                          {
                                              "type": "extension",
                                              "length": 20,
                                              "angle": -2,
                                              "children": [
                                                  {
                                                      "type": "extension",
                                                      "length": 20,
                                                      "angle": -2,
                                                      "children": [
                                                          {
                                                              "type": "extension",
                                                              "length": 20,
                                                              "angle": -2,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667648014703
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667648014102
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667648013338
                                                  },
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667648024325
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 20,
                                                      "angle": 27,
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667648025200
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667648011877
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667648010057
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667646855588
                          },
                          {
                              "type": "extension",
                              "length": 20,
                              "angle": 16,
                              "children": [
                                  {
                                      "type": "leaf",
                                      "children": [],
                                      "taskId": "123981628362",
                                      "time": 1667646914358
                                  },
                                  {
                                      "type": "extension",
                                      "length": 20,
                                      "angle": -31,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667646917916
                                          },
                                          {
                                              "type": "extension",
                                              "length": 20,
                                              "angle": -1,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667646921414
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667646920961
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667646917505
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667646913919
                          }
                      ],
                      "taskId": "123981628362",
                      "time": 1667646852967
                  },
                  {
                      "type": "extension",
                      "length": 50,
                      "angle": -38,
                      "children": [
                          {
                              "type": "leaf",
                              "children": [],
                              "taskId": "123981628362",
                              "time": 1667646859433
                          },
                          {
                              "type": "extension",
                              "length": 26,
                              "angle": -38,
                              "children": [
                                  {
                                      "type": "leaf",
                                      "children": [],
                                      "taskId": "123981628362",
                                      "time": 1667646865016
                                  },
                                  {
                                      "type": "extension",
                                      "length": 26,
                                      "angle": -38,
                                      "children": [
                                          {
                                              "type": "extension",
                                              "length": 30,
                                              "angle": 15,
                                              "children": [
                                                  {
                                                      "type": "extension",
                                                      "length": 30,
                                                      "angle": -7,
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667646872907
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 30,
                                                      "angle": -7,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646878206
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646877421
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 22,
                                                      "angle": -37,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646935805
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 25,
                                                              "angle": -13,
                                                              "children": [
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 25,
                                                                      "angle": 31,
                                                                      "children": [
                                                                          {
                                                                              "type": "leaf",
                                                                              "children": [],
                                                                              "taskId": "123981628362",
                                                                              "time": 1667647895727
                                                                          }
                                                                      ],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667646940683
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667646936596
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646882647
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 47,
                                                      "angle": 22,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667646888931
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667646887809
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 20,
                                                      "angle": 45,
                                                      "children": [
                                                          {
                                                              "type": "extension",
                                                              "length": 20,
                                                              "angle": 45,
                                                              "children": [
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 20,
                                                                      "angle": -40,
                                                                      "children": [
                                                                          {
                                                                              "type": "leaf",
                                                                              "children": [],
                                                                              "taskId": "123981628362",
                                                                              "time": 1667647911726
                                                                          }
                                                                      ],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647907348
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667647904607
                                                          },
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667647909892
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667647903851
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667646869846
                                          },
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667646875662
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667646865539
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667646862182
                          }
                      ],
                      "taskId": "123981628362",
                      "time": 1667646858410
                  },
                  {
                      "type": "extension",
                      "length": 25,
                      "angle": 36,
                      "children": [
                          {
                              "type": "leaf",
                              "children": [],
                              "taskId": "123981628362",
                              "time": 1667646927090
                          },
                          {
                              "type": "extension",
                              "length": 25,
                              "angle": -13,
                              "children": [
                                  {
                                      "type": "leaf",
                                      "children": [],
                                      "taskId": "123981628362",
                                      "time": 1667646932195
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667646931662
                          }
                      ],
                      "taskId": "123981628362",
                      "time": 1667646926638
                  }
              ],
              "taskId": "123981628362",
              "time": 1667646850924
          },
          {
              "type": "extension",
              "length": 25,
              "angle": -38,
              "children": [
                  {
                      "type": "extension",
                      "length": 25,
                      "angle": -17,
                      "children": [
                          {
                              "type": "extension",
                              "length": 25,
                              "angle": 23,
                              "children": [
                                  {
                                      "type": "extension",
                                      "length": 25,
                                      "angle": -30,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667647010365
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667646999691
                                  },
                                  {
                                      "type": "extension",
                                      "length": 20,
                                      "angle": 16,
                                      "children": [
                                          {
                                              "type": "extension",
                                              "length": 20,
                                              "angle": -40,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667647996726
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 20,
                                                      "angle": -40,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667647999020
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 20,
                                                              "angle": -40,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667648000400
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667647999706
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667647997824
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667647995487
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647992349
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667646992447
                          },
                          {
                              "type": "extension",
                              "length": 25,
                              "angle": -32,
                              "children": [
                                  {
                                      "type": "extension",
                                      "length": 25,
                                      "angle": 2,
                                      "children": [
                                          {
                                              "type": "extension",
                                              "length": 25,
                                              "angle": -34,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667647007346
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667647005707
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647002832
                                  },
                                  {
                                      "type": "extension",
                                      "length": 21,
                                      "angle": -35,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667647095845
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647095353
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667646995798
                          },
                          {
                              "type": "extension",
                              "length": 36,
                              "angle": -12,
                              "children": [
                                  {
                                      "type": "leaf",
                                      "children": [],
                                      "taskId": "123981628362",
                                      "time": 1667647879841
                                  },
                                  {
                                      "type": "extension",
                                      "length": 55,
                                      "angle": -12,
                                      "children": [
                                          {
                                              "type": "extension",
                                              "length": 55,
                                              "angle": -12,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667647889165
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667647888281
                                          },
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667647892334
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647886051
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667647878602
                          }
                      ],
                      "taskId": "123981628362",
                      "time": 1667646988724
                  },
                  {
                      "type": "extension",
                      "length": 21,
                      "angle": -45,
                      "children": [
                          {
                              "type": "extension",
                              "length": 21,
                              "angle": -45,
                              "children": [
                                  {
                                      "type": "extension",
                                      "length": 21,
                                      "angle": 8,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667647194169
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647144212
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667647138699
                          }
                      ],
                      "taskId": "123981628362",
                      "time": 1667647102064
                  }
              ],
              "taskId": "123981628362",
              "time": 1667646985833
          },
          {
              "type": "extension",
              "length": 25,
              "angle": 38,
              "children": [
                  {
                      "type": "extension",
                      "length": 25,
                      "angle": 38,
                      "children": [
                          {
                              "type": "extension",
                              "length": 25,
                              "angle": -26,
                              "children": [
                                  {
                                      "type": "extension",
                                      "length": 25,
                                      "angle": -26,
                                      "children": [
                                          {
                                              "type": "extension",
                                              "length": 25,
                                              "angle": -14,
                                              "children": [
                                                  {
                                                      "type": "extension",
                                                      "length": 25,
                                                      "angle": -14,
                                                      "children": [
                                                          {
                                                              "type": "extension",
                                                              "length": 25,
                                                              "angle": 24,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647037566
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667647030015
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667647022240
                                                  },
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667647080590
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 21,
                                                      "angle": 12,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667647083143
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 21,
                                                              "angle": 12,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647084632
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667647084222
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667647082585
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667647021997
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647018103
                                  },
                                  {
                                      "type": "extension",
                                      "length": 25,
                                      "angle": -45,
                                      "children": [
                                          {
                                              "type": "extension",
                                              "length": 32,
                                              "angle": -22,
                                              "children": [
                                                  {
                                                      "type": "leaf",
                                                      "children": [],
                                                      "taskId": "123981628362",
                                                      "time": 1667647050833
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 32,
                                                      "angle": 9,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667647054821
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 32,
                                                              "angle": 9,
                                                              "children": [
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 21,
                                                                      "angle": -20,
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647059788
                                                                  },
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647062218
                                                                  },
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 21,
                                                                      "angle": -20,
                                                                      "children": [
                                                                          {
                                                                              "type": "leaf",
                                                                              "children": [],
                                                                              "taskId": "123981628362",
                                                                              "time": 1667647065231
                                                                          }
                                                                      ],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647064761
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667647055854
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667647054022
                                                  },
                                                  {
                                                      "type": "extension",
                                                      "length": 21,
                                                      "angle": -20,
                                                      "children": [
                                                          {
                                                              "type": "leaf",
                                                              "children": [],
                                                              "taskId": "123981628362",
                                                              "time": 1667647071413
                                                          },
                                                          {
                                                              "type": "extension",
                                                              "length": 21,
                                                              "angle": 12,
                                                              "children": [
                                                                  {
                                                                      "type": "leaf",
                                                                      "children": [],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647074687
                                                                  },
                                                                  {
                                                                      "type": "extension",
                                                                      "length": 21,
                                                                      "angle": 12,
                                                                      "children": [
                                                                          {
                                                                              "type": "leaf",
                                                                              "children": [],
                                                                              "taskId": "123981628362",
                                                                              "time": 1667647077917
                                                                          }
                                                                      ],
                                                                      "taskId": "123981628362",
                                                                      "time": 1667647077530
                                                                  }
                                                              ],
                                                              "taskId": "123981628362",
                                                              "time": 1667647074136
                                                          }
                                                      ],
                                                      "taskId": "123981628362",
                                                      "time": 1667647070746
                                                  }
                                              ],
                                              "taskId": "123981628362",
                                              "time": 1667647050379
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647025961
                                  },
                                  {
                                      "type": "extension",
                                      "length": 25,
                                      "angle": 24,
                                      "children": [
                                          {
                                              "type": "leaf",
                                              "children": [],
                                              "taskId": "123981628362",
                                              "time": 1667647034341
                                          }
                                      ],
                                      "taskId": "123981628362",
                                      "time": 1667647033914
                                  }
                              ],
                              "taskId": "123981628362",
                              "time": 1667647017619
                          }
                      ],
                      "taskId": "123981628362",
                      "time": 1667647014897
                  },
                  {
                      "type": "leaf",
                      "children": [],
                      "taskId": "123981628362",
                      "time": 1667647528957
                  },
                  {
                      "type": "extension",
                      "length": 21,
                      "angle": -11,
                      "children": [],
                      "taskId": "123981628362",
                      "time": 1667647529445
                  }
              ],
              "taskId": "123981628362",
              "time": 1667647014588
          }
      ],
      "taskId": "",
      "time": 1667646845144
  }
]